USE colony;
DROP FUNCTION IF EXISTS FixDate;
CREATE FUNCTION FixDate(d DATE)
    RETURNS DATE DETERMINISTIC
    RETURN 
    STR_TO_DATE(concat_Ws('-', case WHEN YEAR(d)=0 THEN '0001' else cast(YEAR(d) AS CHAR) END,
    CASE WHEN MONTH(d)=0 THEN '01' ELSE cast(MONTH(d) AS CHAR) END ,
    CASE WHEN DAY(d)=0 THEN '01' ELSE CAST(DAY(d) AS CHAR) END), '%Y-%m-%d');
