#!/bin/bash
#assume that some process initialized from mysql has dumped text files. Those files should be
#generated by a command like this:
#
# mysqldump -u username --password=xxxx --tab=$MYSQL_DUMPDIR --no-create-info colony --ignore-table=tmp_table
#
# Note that MYSQL_DUMPDIR in that case must be relative to the mysql SERVER, as the server
# itself is dumping the files
#
# DUMPDIR as a directory relative to THIS script. Change following line:
#
DUMPDIR=primate-dump
FIXEDDIR=fixed

POSTGRES_DB=trunk
POSTGRES_PASS=sasa

#
# Iterate over the dumped text files.
for dumpfile in $DUMPDIR/*.txt
do
  fname=${dumpfile##*/}
  basename=${fname%%.*}
  echo "fixtabs $fname" 
  if [ ! -f ${FIXEDDIR}/$fname ]; then
      java FixTabs < $dumpfile > ${FIXEDDIR}/$fname
      if [ $? -ne 0 ]; then
         echo "Error fixing $fname" >&2
         exit 1
      fi

      echo "psql TRUNCATE colony.$basename" 
      psql -U postgres -d ${POSTGRES_DB} -c "TRUNCATE colony.$basename;" 
      if [ $? -ne 0 ]; then
         echo "Error truncating colony.$basename; Perhaps security error?"  >&2
         exit 1
      fi

      echo "copy colony.$basename FROM ${FIXEDDIR}/$fname" 
      psql -U postgres -d ${POSTGRES_DB} -c "\copy colony.$basename FROM '${FIXEDDIR}/$fname'"  
      if [ $? -ne 0 ]; then
         echo "Error copying data see errors.log for details" >&2
         exit 1
      fi
  fi
  echo
done

echo "Load successful!"
exit 0
